/**
 * UI End-to-End Tests
 *
 * Tests the frontend UI flows for Projects, Campaigns, and Publish.
 * These tests exercise the browser UI at http://localhost:3000.
 *
 * Note: The frontend currently uses mock-projects.ts (sessionStorage).
 * IDs generated by mock-projects have the form "project-{uuid}".
 * Once the frontend is wired to the real backend APIs these tests remain valid.
 */
import { test, expect } from "@playwright/test";

const FRONTEND = "http://localhost:3000";
const API = "http://localhost:8000/api/v1";

// project IDs from mock-projects use "project-{uuid}" prefix
const PROJECT_ID_RE = /\/projects\/project-[0-9a-f-]+$/;

// ---------------------------------------------------------------------------
// Landing Page
// ---------------------------------------------------------------------------
test.describe("Landing Page", () => {
  test("loads and shows hero section", async ({ page }) => {
    await page.goto(FRONTEND);
    await expect(page).toHaveTitle(/marketing/i);
    await expect(page.locator("main")).toBeVisible();
  });

  test("no console errors on load", async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(FRONTEND);
    await page.waitForLoadState("networkidle");
    const critical = errors.filter(
      (e) => !e.includes("hydration") && !e.includes("ResizeObserver")
    );
    expect(critical).toHaveLength(0);
  });

  test("navbar is visible", async ({ page }) => {
    await page.goto(FRONTEND);
    await expect(page.locator("nav")).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Create Project Flow
// ---------------------------------------------------------------------------
test.describe("Create Project", () => {
  test("navigating to /projects/new shows the create form", async ({ page }) => {
    await page.goto(`${FRONTEND}/projects/new`);
    await expect(page.locator("#project-name")).toBeVisible();
    await expect(page.locator("#project-description")).toBeVisible();
    await expect(page.locator('button[type="submit"]')).toBeVisible();
    await expect(page.locator('button[type="submit"]')).toHaveText("Create project");
  });

  test("submitting empty name shows validation error", async ({ page }) => {
    await page.goto(`${FRONTEND}/projects/new`);
    await page.locator('button[type="submit"]').click();
    await expect(page.locator("text=Project name is required")).toBeVisible();
  });

  test("filling in name and submitting redirects to project page", async ({ page }) => {
    await page.goto(`${FRONTEND}/projects/new`);
    await page.locator("#project-name").fill("UI Test Project");
    await page.locator("#project-description").fill("Created by Playwright");
    await page.locator('button[type="submit"]').click();
    await page.waitForURL(PROJECT_ID_RE, { timeout: 5000 });
    expect(page.url()).toMatch(PROJECT_ID_RE);
  });

  test("project workspace shows project name after creation", async ({ page }) => {
    await page.goto(`${FRONTEND}/projects/new`);
    await page.locator("#project-name").fill("Named Project For Test");
    await page.locator('button[type="submit"]').click();
    await page.waitForURL(PROJECT_ID_RE, { timeout: 5000 });
    await expect(page.locator("h1", { hasText: "Named Project For Test" })).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Project Workspace
// ---------------------------------------------------------------------------
test.describe("Project Workspace", () => {
  let projectUrl: string;

  test.beforeEach(async ({ page }) => {
    await page.goto(`${FRONTEND}/projects/new`);
    await page.locator("#project-name").fill("Workspace Test Project");
    await page.locator('button[type="submit"]').click();
    await page.waitForURL(PROJECT_ID_RE, { timeout: 5000 });
    projectUrl = page.url();
  });

  test("workspace header shows project name and Publish button", async ({ page }) => {
    await page.goto(projectUrl);
    await expect(page.locator("h1", { hasText: "Workspace Test Project" })).toBeVisible();
    await expect(page.locator("a", { hasText: "Publish to social" })).toBeVisible();
  });

  test("Publish to social link navigates to publish page", async ({ page }) => {
    await page.goto(projectUrl);
    await page.locator("a", { hasText: "Publish to social" }).click();
    await page.waitForURL(/\/publish$/, { timeout: 5000 });
    expect(page.url()).toContain("/publish");
  });

  test("publish page loads without errors", async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", (e) => errors.push(e.message));
    const projectId = projectUrl.split("/projects/")[1];
    await page.goto(`${FRONTEND}/projects/${projectId}/publish`);
    await page.waitForLoadState("networkidle");
    const critical = errors.filter(
      (e) => !e.includes("hydration") && !e.includes("ResizeObserver")
    );
    expect(critical).toHaveLength(0);
  });

  test("back button returns to home", async ({ page }) => {
    await page.goto(projectUrl);
    const backLink = page.locator("a", { hasText: "← Home" });
    if (await backLink.isVisible()) {
      await backLink.click();
      await expect(page).toHaveURL(FRONTEND + "/");
    }
  });
});

// ---------------------------------------------------------------------------
// Campaign Creation
// ---------------------------------------------------------------------------
test.describe("Campaign Creation", () => {
  test("/campaigns/new redirects to /projects/new", async ({ page }) => {
    await page.goto(`${FRONTEND}/campaigns/new`);
    await page.waitForURL(/\/projects\/new/, { timeout: 5000 });
    expect(page.url()).toContain("/projects/new");
  });
});

// ---------------------------------------------------------------------------
// API reachability from browser
// ---------------------------------------------------------------------------
test.describe("API reachability (browser fetch)", () => {
  test("frontend can fetch /api/v1/health", async ({ page }) => {
    const response = await page.request.get(`${API}/health`);
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.status).toBe("ok");
  });

  test("backend OpenAPI docs are accessible", async ({ page }) => {
    await page.goto("http://localhost:8000/docs");
    await expect(page.locator("body")).toBeVisible();
  });

  test("backend lists new project routes in OpenAPI spec", async ({ page }) => {
    const response = await page.request.get("http://localhost:8000/openapi.json");
    expect(response.status()).toBe(200);
    const spec = await response.json();
    const paths = Object.keys(spec.paths ?? {});
    expect(paths.some((p) => p.includes("/projects"))).toBe(true);
    expect(paths.some((p) => p.includes("/publish"))).toBe(true);
    expect(paths.some((p) => p.includes("/platforms"))).toBe(true);
  });

  test("CORS allows frontend origin on /api/v1/projects", async ({ page }) => {
    const res = await page.request.get(`${API}/projects?user_id=cors-test`, {
      headers: { Origin: "http://localhost:3000" },
    });
    expect([200, 422]).toContain(res.status());
    const corsHeader = res.headers()["access-control-allow-origin"];
    expect(corsHeader).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// Full integration path: Create project via API → view in UI
// ---------------------------------------------------------------------------
test.describe("Full integration path", () => {
  let integrationProjectId: string;

  test("create project via API then view workspace in browser", async ({ page, request }) => {
    const createRes = await request.post(`${API}/projects`, {
      data: {
        user_id: "ui-integration-user",
        name: "Integration Test Project",
        description: "Created via API, viewed in browser",
      },
    });
    expect(createRes.status()).toBe(201);
    const project = await createRes.json();
    integrationProjectId = project.id;

    await page.goto(`${FRONTEND}/projects/${integrationProjectId}`);
    await expect(page.locator("body")).toBeVisible();
  });

  test("create campaign via API then view campaign page in browser", async ({
    page,
    request,
  }) => {
    const projectRes = await request.post(`${API}/projects`, {
      data: { user_id: "ui-integration-user", name: "Campaign View Test" },
    });
    const project = await projectRes.json();

    const campaignRes = await request.post(`${API}/campaigns`, {
      data: {
        user_id: "ui-integration-user",
        title: "Playwright Test Campaign",
        brief: "A campaign created during Playwright integration testing.",
        project_id: project.id,
      },
    });
    expect(campaignRes.status()).toBe(201);
    const campaign = await campaignRes.json();
    expect(campaign.project_id).toBe(project.id);

    await page.goto(`${FRONTEND}/campaigns/${campaign.id}`);
    await expect(page.locator("body")).toBeVisible();

    await request.delete(`${API}/projects/${project.id}`);
  });

  test.afterAll(async ({ request }) => {
    if (integrationProjectId) {
      await request.delete(`${API}/projects/${integrationProjectId}`);
    }
  });
});
